"""Added PortalSessionCreate to models

Revision ID: 2018216f787d
Revises: 9fa19d384f52
Create Date: 2025-03-21 10:53:04.377282

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2018216f787d'
down_revision = '9fa19d384f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
