"""changed message to generic message, duplicate name models

Revision ID: 2545f1a2753f
Revises: 997a91afe86d
Create Date: 2025-03-25 10:25:34.346728

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2545f1a2753f'
down_revision = '997a91afe86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
