"""changed sub

Revision ID: 7cdb0583d714
Revises: 78de4f58b1f0
Create Date: 2025-03-12 21:07:30.693674

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7cdb0583d714'
down_revision = '78de4f58b1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripecustomer',
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripecustomer_stripe_customer_id'), 'stripecustomer', ['stripe_customer_id'], unique=False)
    op.create_table('stripepayment',
    sa.Column('stripe_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('payment_method_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['stripecustomer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripepayment_stripe_payment_id'), 'stripepayment', ['stripe_payment_id'], unique=False)
    op.alter_column('stripeprice', 'recurring_interval',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_constraint('stripeprice_stripe_price_id_key', 'stripeprice', type_='unique')
    op.create_index(op.f('ix_stripeprice_stripe_price_id'), 'stripeprice', ['stripe_price_id'], unique=False)
    op.drop_constraint('stripeprice_product_id_fkey', 'stripeprice', type_='foreignkey')
    op.create_foreign_key(None, 'stripeprice', 'stripeproduct', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('stripeproduct_stripe_product_id_key', 'stripeproduct', type_='unique')
    op.create_index(op.f('ix_stripeproduct_stripe_product_id'), 'stripeproduct', ['stripe_product_id'], unique=False)
    op.add_column('stripesubscription', sa.Column('customer_id', sa.Uuid(), nullable=False))
    op.alter_column('stripesubscription', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.drop_constraint('stripesubscription_stripe_subscription_id_key', 'stripesubscription', type_='unique')
    op.create_index(op.f('ix_stripesubscription_stripe_subscription_id'), 'stripesubscription', ['stripe_subscription_id'], unique=True)
    op.create_foreign_key(None, 'stripesubscription', 'stripecustomer', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stripesubscription', type_='foreignkey')
    op.drop_index(op.f('ix_stripesubscription_stripe_subscription_id'), table_name='stripesubscription')
    op.create_unique_constraint('stripesubscription_stripe_subscription_id_key', 'stripesubscription', ['stripe_subscription_id'])
    op.alter_column('stripesubscription', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('stripesubscription', 'customer_id')
    op.drop_index(op.f('ix_stripeproduct_stripe_product_id'), table_name='stripeproduct')
    op.create_unique_constraint('stripeproduct_stripe_product_id_key', 'stripeproduct', ['stripe_product_id'])
    op.drop_constraint(None, 'stripeprice', type_='foreignkey')
    op.create_foreign_key('stripeprice_product_id_fkey', 'stripeprice', 'stripeproduct', ['product_id'], ['id'])
    op.drop_index(op.f('ix_stripeprice_stripe_price_id'), table_name='stripeprice')
    op.create_unique_constraint('stripeprice_stripe_price_id_key', 'stripeprice', ['stripe_price_id'])
    op.alter_column('stripeprice', 'recurring_interval',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_index(op.f('ix_stripepayment_stripe_payment_id'), table_name='stripepayment')
    op.drop_table('stripepayment')
    op.drop_index(op.f('ix_stripecustomer_stripe_customer_id'), table_name='stripecustomer')
    op.drop_table('stripecustomer')
    # ### end Alembic commands ###
