"""add conversation relationships

Revision ID: 997a91afe86d
Revises: d50f32da3125
Create Date: 2025-03-25 10:00:05.031527

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '997a91afe86d'
down_revision = 'd50f32da3125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
