"""added tons of stuff in models for user profiling checking and cleaning after.

Revision ID: ab2d74005635
Revises: d920fafd645a
Create Date: 2025-04-07 11:14:59.699448

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ab2d74005635'
down_revision = 'd920fafd645a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_metadata', sa.JSON(), nullable=True))
    op.add_column('usergoal', sa.Column('mi_related', sa.Boolean(), nullable=False))
    op.add_column('userinsight', sa.Column('mi_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userprofile', sa.Column('recovery_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userprofile', sa.Column('psychological_traits', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'psychological_traits')
    op.drop_column('userprofile', 'recovery_stage')
    op.drop_column('userinsight', 'mi_stage')
    op.drop_column('usergoal', 'mi_related')
    op.drop_column('message', 'message_metadata')
    # ### end Alembic commands ###
