"""added and changed for full openai integration with user profiling

Revision ID: b30b26cd752c
Revises: f7459feab8f5
Create Date: 2025-04-10 13:11:06.972798

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b30b26cd752c'
down_revision = 'f7459feab8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
