"""Added UserProfile, UserInsight, UserGoal, UserNotification

Revision ID: d920fafd645a
Revises: 2545f1a2753f
Create Date: 2025-04-03 11:28:03.570899

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd920fafd645a'
down_revision = '2545f1a2753f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usergoal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_notification_sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usergoal_user_id'), 'usergoal', ['user_id'], unique=False)
    op.create_table('usernotification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notification_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('was_sent', sa.Boolean(), nullable=False),
    sa.Column('was_opened', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usernotification_user_id'), 'usernotification', ['user_id'], unique=False)
    op.create_table('userprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('therapist_gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('addiction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('abstinence_days', sa.Integer(), nullable=False),
    sa.Column('abstinence_start_date', sa.DateTime(), nullable=True),
    sa.Column('relapse_risk_score', sa.Integer(), nullable=True),
    sa.Column('motivation_level', sa.Integer(), nullable=True),
    sa.Column('big_five_scores', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userprofile_user_id'), 'userprofile', ['user_id'], unique=True)
    op.create_table('userinsight',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('insight_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_of_week', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('time_of_day', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emotional_significance', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['userprofile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userinsight_conversation_id'), 'userinsight', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_userinsight_profile_id'), 'userinsight', ['profile_id'], unique=False)
    op.create_index(op.f('ix_userinsight_user_id'), 'userinsight', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userinsight_user_id'), table_name='userinsight')
    op.drop_index(op.f('ix_userinsight_profile_id'), table_name='userinsight')
    op.drop_index(op.f('ix_userinsight_conversation_id'), table_name='userinsight')
    op.drop_table('userinsight')
    op.drop_index(op.f('ix_userprofile_user_id'), table_name='userprofile')
    op.drop_table('userprofile')
    op.drop_index(op.f('ix_usernotification_user_id'), table_name='usernotification')
    op.drop_table('usernotification')
    op.drop_index(op.f('ix_usergoal_user_id'), table_name='usergoal')
    op.drop_table('usergoal')
    # ### end Alembic commands ###
