"""changed relationships for user(userbase) fixed docker error prestart

Revision ID: f42d091b32d6
Revises: d920fafd645a
Create Date: 2025-04-04 07:29:52.386587

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f42d091b32d6'
down_revision = 'd920fafd645a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedulednotification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('related_entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedulednotification_user_id'), 'schedulednotification', ['user_id'], unique=False)
    op.create_table('usernotificationsettings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_reminders', sa.Boolean(), nullable=False),
    sa.Column('abstinence_milestones', sa.Boolean(), nullable=False),
    sa.Column('risk_alerts', sa.Boolean(), nullable=False),
    sa.Column('daily_check_ins', sa.Boolean(), nullable=False),
    sa.Column('coping_strategies', sa.Boolean(), nullable=False),
    sa.Column('educational_content', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quiet_hours_end', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferred_time_morning', sa.Boolean(), nullable=False),
    sa.Column('preferred_time_afternoon', sa.Boolean(), nullable=False),
    sa.Column('preferred_time_evening', sa.Boolean(), nullable=False),
    sa.Column('max_notifications_per_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usernotificationsettings_user_id'), 'usernotificationsettings', ['user_id'], unique=True)
    op.create_table('usernotificationengagement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('engaged', sa.Boolean(), nullable=False),
    sa.Column('engagement_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['usernotification.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usernotificationengagement_notification_id'), 'usernotificationengagement', ['notification_id'], unique=False)
    op.create_index(op.f('ix_usernotificationengagement_user_id'), 'usernotificationengagement', ['user_id'], unique=False)
    op.add_column('usernotification', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usernotification', 'created_at')
    op.drop_index(op.f('ix_usernotificationengagement_user_id'), table_name='usernotificationengagement')
    op.drop_index(op.f('ix_usernotificationengagement_notification_id'), table_name='usernotificationengagement')
    op.drop_table('usernotificationengagement')
    op.drop_index(op.f('ix_usernotificationsettings_user_id'), table_name='usernotificationsettings')
    op.drop_table('usernotificationsettings')
    op.drop_index(op.f('ix_schedulednotification_user_id'), table_name='schedulednotification')
    op.drop_table('schedulednotification')
    # ### end Alembic commands ###
