"""changed a bit to allow none for user profiling 

Revision ID: f7459feab8f5
Revises: ab2d74005635
Create Date: 2025-04-08 13:35:48.191532

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f7459feab8f5'
down_revision = 'ab2d74005635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
